# ビルドステージ
ARG NODE_VER
FROM node:${NODE_VER} AS build
WORKDIR /home/node/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# 本番用ステージ
FROM nginx:latest
COPY --from=build /home/node/app/dist /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/certs /etc/nginx/certs

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
