version: '3.7'

services:

  frontend:
    build:
      args:
        - NODE_VER=18.15.0-slim
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    tty: true
    volumes:
      - ./frontend:/home/node/app
    ports:
      - 5173:80
    networks:
      - app-network
    restart: always
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    volumes:
      - ./backend/:/go/src/app
    ports:
      - "8080:8080"
    networks:
      - app-network
      - db-network
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8080/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${PGPASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    networks:
      - db-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    networks:
      - db-network
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

networks:
  app-network:
  db-network:
