version: '3'

services:

  frontend:
    build:
      args:
        - NODE_VER=16.17.1-slim
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173

  backend:
    build: backend
    volumes:
      - ./backend/:/go/src/app
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${PGPASSWORD}
      TZ: "Asia/Tokyo"
    restart: always
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  node_modules:
